name: Build and Deploy Hugo Site

on:
  push:
    branches:
      - main  # 当推送到 main 分支时触发工作流

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # 使用兼容 Node.js 20 的版本

    - name: Install Hugo
      run: |
        HUGO_VERSION=0.118.2  # 设置您需要的 Hugo 版本
        wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz
        tar -xzf hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz
        sudo mv hugo /usr/local/bin/
        hugo version  # 验证 Hugo 是否正确安装

    - name: Build
      run: hugo --minify

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4  # 兼容 Node.js 20 的部署动作
      with:
        token: ${{ secrets.GITHUB_TOKEN }}  # 确保参数名称为 'token'
        branch: gh-pages  # 部署的分支
        folder: public  # Hugo 构建输出的目录

