name: Build and Deploy Hugo Site

on:
  push:
    branches:
      - main  # 当推送到 main 分支时触发该工作流

jobs:
  build:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 作为执行环境

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # 更新到 v3

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2  # 使用支持 Node.js 20 的 Hugo Action
      with:
        hugo-version: 'extended'  # 指定使用扩展版 Hugo

    - name: Build
      run: hugo --minify  # 构建 Hugo 网站，带有最小化选项

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3  # 使用 GitHub Pages 部署
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}  # GitHub 提供的访问令牌
        publish_dir: ./public  # Hugo 构建后的文件会放在 `public/` 文件夹中

